name: first workflow
on:
  push:
    branches:
      - "main"

jobs:
  first-workflow-job: 
    name: first-job
    runs-on: ubuntu-latest
    run: ls

    steps:
      - name: run bash command
        run: echo "first workflow"
        run: ls
        shell: bash
